### ISSUE TITLE
USB IDs

### ISSUE THREAD

**Issue by vulpes2** [polhenarejos/pico-hsm#32]
You can get a free USB PID allocated with the openmoko VID here: https://github.com/openmoko/openmoko-usb-oui

> By applying for an Openmoko Product ID, you acknowledge that either
> 
> - the USB device you are developing is an open hardware project (as per the OSHW Definition), or
> - the firmware/software running on your USB device is Free / Open Source software, licensed under an OSI-Approved, FSF-Recognized or DFSG-Approved Free / Open Source software license

pico-hsm satisfies the second condition, and I think it would be a good idea to get a PID for the project to avoid all the ID patching step moving forward.

**Comment by polhenarejos** [comment]
The problem is not about having a free VID&PID, as there many vendors offering spare PID for free. The main stopping point is that IFD/CCID driver is shipped with a predefined set of VID&PID and some Yubico, Cardcontact and Nitrokey tools are looking for specific VID&PID. Patching the firmware might be tedious but it is more faster compared to waiting 3rd party platforms to ship upgraded software with new PIDs.
