### ISSUE TITLE
Failing to detect pico hsm

### ISSUE THREAD

**Issue by jayeye** [polhenarejos/pico-hsm#8]
I should RTFM before submitting issues :(

My misunderstanding was that the device should be detectable at any VID:PID, not at the specific ones that opensc expected. Using 234b:0000 solved the problem. And since this is for personal use, I don't have to worry about acquiring my own vid.

**Comment by rrottmann** [comment]
This is due to the VID:PID. It needs to be patched to a value that is supported and understood by ccid. You could use the Test VID:PID of Free Software Initiative of Japan as described in the Readme. Unfortunately, VID:PID cannot be easily distributed without acquiring an own one and the testing values have to be used by the user as part of the usage contract. See https://github.com/polhenarejos/pico-hsm#download for how to change the VID:PID.

**Comment by jayeye** [comment]
> This is due to the VID:PID. It needs to be patched to a value that is supported and understood by ccid. You could use the Test VID:PID of Free Software Initiative of Japan as described in the Readme. Unfortunately, VID:PID cannot be easily distributed without acquiring an own one and the testing values have to be used by the user as part of the usage contract. See https://github.com/polhenarejos/pico-hsm#download for how to change the VID:PID.

Thanks, just saw this after I edited my original message.
